
AstralKeys = {
	{
		["dungeon_id"] = 382,
		["week"] = 261,
		["class"] = "MAGE",
		["weekly_best"] = 0,
		["time_stamp"] = 8758,
		["key_level"] = 15,
		["unit"] = "Proctorb-Mal'Ganis",
	}, -- [1]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "PALADIN",
		["key_level"] = 16,
		["unit"] = "Leylìn-Mal'Ganis",
		["dungeon_id"] = 381,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 1,
	}, -- [2]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "SHAMAN",
		["key_level"] = 15,
		["unit"] = "Pandathrall-Mal'Ganis",
		["dungeon_id"] = 379,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 3880,
	}, -- [3]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "WARRIOR",
		["key_level"] = 18,
		["unit"] = "Rageboner-Mal'Ganis",
		["dungeon_id"] = 378,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 3,
	}, -- [4]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "PRIEST",
		["key_level"] = 22,
		["unit"] = "Pandaprìest-Mal'Ganis",
		["dungeon_id"] = 378,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 6,
	}, -- [5]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "DEATHKNIGHT",
		["key_level"] = 19,
		["unit"] = "Pandadk-Mal'Ganis",
		["dungeon_id"] = 392,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 1385,
	}, -- [6]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "DRUID",
		["key_level"] = 20,
		["unit"] = "Jackychankla-Mal'Ganis",
		["dungeon_id"] = 379,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 1,
	}, -- [7]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "MONK",
		["key_level"] = 23,
		["unit"] = "Jackychancla-Mal'Ganis",
		["dungeon_id"] = 377,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 1358,
	}, -- [8]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "DEMONHUNTER",
		["key_level"] = 20,
		["unit"] = "Forbins-Mal'Ganis",
		["dungeon_id"] = 380,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 1479,
	}, -- [9]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "MAGE",
		["key_level"] = 15,
		["unit"] = "Majinpohner-Mal'Ganis",
		["dungeon_id"] = 392,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 2,
	}, -- [10]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "DRUID",
		["key_level"] = 15,
		["unit"] = "Whiteclohner-Mal'Ganis",
		["dungeon_id"] = 376,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 1,
	}, -- [11]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "HUNTER",
		["key_level"] = 19,
		["unit"] = "Pohner-Mal'Ganis",
		["dungeon_id"] = 379,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 2,
	}, -- [12]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "DRUID",
		["key_level"] = 20,
		["unit"] = "Yenstah-Mal'Ganis",
		["dungeon_id"] = 378,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 2,
	}, -- [13]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "DEMONHUNTER",
		["key_level"] = 20,
		["unit"] = "Adamddh-Mal'Ganis",
		["dungeon_id"] = 375,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 2,
	}, -- [14]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "PALADIN",
		["key_level"] = 20,
		["unit"] = "Ohner-Mal'Ganis",
		["dungeon_id"] = 377,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 1,
	}, -- [15]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "DRUID",
		["key_level"] = 16,
		["unit"] = "Threatdown-Mal'Ganis",
		["dungeon_id"] = 379,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 1675,
	}, -- [16]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "MONK",
		["key_level"] = 16,
		["unit"] = "Trashbandito-Mal'Ganis",
		["dungeon_id"] = 381,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 17127,
	}, -- [17]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "HUNTER",
		["key_level"] = 21,
		["unit"] = "Rickibobbi-Mal'Ganis",
		["dungeon_id"] = 382,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 2,
	}, -- [18]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "DEATHKNIGHT",
		["key_level"] = 16,
		["unit"] = "Chokela-Mal'Ganis",
		["dungeon_id"] = 379,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 2,
	}, -- [19]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "WARLOCK",
		["key_level"] = 19,
		["unit"] = "Dokdok-Mal'Ganis",
		["dungeon_id"] = 380,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 2,
	}, -- [20]
	{
		["source"] = "guild",
		["weekly_best"] = 0,
		["class"] = "HUNTER",
		["key_level"] = 18,
		["unit"] = "Lelliana-Mal'Ganis",
		["dungeon_id"] = 377,
		["week"] = 261,
		["faction"] = 1,
		["time_stamp"] = 3937,
	}, -- [21]
}
AstralCharacters = {
	{
		["weekly_best"] = 0,
		["class"] = "MONK",
		["faction"] = 1,
		["unit"] = "Trashbandito-Mal'Ganis",
	}, -- [1]
	{
		["weekly_best"] = 0,
		["class"] = "DEMONHUNTER",
		["faction"] = 1,
		["unit"] = "Forbins-Mal'Ganis",
	}, -- [2]
	{
		["weekly_best"] = 0,
		["class"] = "HUNTER",
		["unit"] = "Lelliana-Mal'Ganis",
		["faction"] = 1,
	}, -- [3]
	{
		["weekly_best"] = 0,
		["class"] = "MAGE",
		["unit"] = "Proctorb-Mal'Ganis",
		["faction"] = 1,
	}, -- [4]
	{
		["weekly_best"] = 0,
		["class"] = "DRUID",
		["unit"] = "Threatdown-Mal'Ganis",
		["faction"] = 1,
	}, -- [5]
}
AstralKeysSettings = {
	["wipedOldTables"] = true,
	["general"] = {
		["show_minimap_button"] = {
			["isEnabled"] = true,
		},
		["init_time"] = 1658847600,
		["expanded_tooltip"] = {
			["isEnabled"] = true,
		},
		["report_on_message"] = {
			["raid"] = false,
			["party"] = true,
			["no_key"] = true,
			["guild"] = false,
		},
		["show_tooltip_key"] = {
			["isEnabled"] = true,
		},
		["announce_party"] = {
			["isEnabled"] = true,
		},
		["announce_guild"] = {
			["isEnabled"] = false,
		},
	},
	["frame"] = {
		["rank_filter"] = {
			true, -- [1]
			true, -- [2]
			true, -- [3]
			true, -- [4]
			true, -- [5]
			true, -- [6]
			true, -- [7]
			true, -- [8]
			true, -- [9]
			true, -- [10]
		},
		["current_list"] = "GUILD",
		["isCollapsed"] = {
			["isEnabled"] = false,
		},
		["orientation"] = 0,
		["mingle_offline"] = {
			["isEnabled"] = true,
		},
		["sorth_method"] = "dungeon_name",
		["show_offline"] = {
			["isEnabled"] = true,
		},
	},
	["friendOptions"] = {
		["friend_sync"] = {
			["isEnabled"] = true,
		},
		["show_other_faction"] = {
			["isEnabled"] = true,
		},
	},
	["new_settings_config"] = true,
}
AstralMinimap = {
	["profileKeys"] = {
		["Proctorb - Mal'Ganis"] = "Proctorb - Mal'Ganis",
		["Forbizzle - Bleeding Hollow"] = "Forbizzle - Bleeding Hollow",
		["Lionarddo - Bleeding Hollow"] = "Lionarddo - Bleeding Hollow",
		["Stareitheta - Stormrage"] = "Stareitheta - Stormrage",
		["Forbinor - Mal'Ganis"] = "Forbinor - Mal'Ganis",
		["Forbinai - Mal'Ganis"] = "Forbinai - Mal'Ganis",
		["Itisame - Stormrage"] = "Itisame - Stormrage",
		["Forbs - Bleeding Hollow"] = "Forbs - Bleeding Hollow",
		["Forbs - Stormrage"] = "Forbs - Stormrage",
		["Forbiñ - Mal'Ganis"] = "Forbiñ - Mal'Ganis",
		["Daclampers - Stormrage"] = "Daclampers - Stormrage",
		["Forbizzle - Lightning's Blade"] = "Forbizzle - Lightning's Blade",
		["Forbpal - Mal'Ganis"] = "Forbpal - Mal'Ganis",
		["Forbot - Mal'Ganis"] = "Forbot - Mal'Ganis",
		["Worgentime - Mal'Ganis"] = "Worgentime - Mal'Ganis",
		["Saraessa - Mal'Ganis"] = "Saraessa - Mal'Ganis",
		["Peroielor - Stormrage"] = "Peroielor - Stormrage",
		["Forbinsham - Mal'Ganis"] = "Forbinsham - Mal'Ganis",
		["Lelliana - Mal'Ganis"] = "Lelliana - Mal'Ganis",
		["Telanvier - Mal'Ganis"] = "Telanvier - Mal'Ganis",
		["Forbins - Mal'Ganis"] = "Forbins - Mal'Ganis",
		["Threatdown - Mal'Ganis"] = "Threatdown - Mal'Ganis",
		["Thatsabart - Mal'Ganis"] = "Thatsabart - Mal'Ganis",
		["Trashbandito - Mal'Ganis"] = "Trashbandito - Mal'Ganis",
		["Ducker - Bleeding Hollow"] = "Ducker - Bleeding Hollow",
		["Garradagh - Stormrage"] = "Garradagh - Stormrage",
		["Olokrim - Mal'Ganis"] = "Olokrim - Mal'Ganis",
		["Haruon - Mal'Ganis"] = "Haruon - Mal'Ganis",
	},
	["profiles"] = {
		["Proctorb - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 342.838123624278,
			},
		},
		["Forbizzle - Bleeding Hollow"] = {
			["minimap"] = {
				["minimapPos"] = 14.3493173321231,
			},
		},
		["Lionarddo - Bleeding Hollow"] = {
		},
		["Stareitheta - Stormrage"] = {
		},
		["Forbinor - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 354.4434475721029,
			},
		},
		["Forbinai - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 343.790956209497,
			},
		},
		["Itisame - Stormrage"] = {
			["minimap"] = {
				["minimapPos"] = 343.9399451867468,
			},
		},
		["Forbs - Bleeding Hollow"] = {
		},
		["Forbs - Stormrage"] = {
			["minimap"] = {
				["minimapPos"] = 352.673611167285,
			},
		},
		["Forbiñ - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 348.835159770943,
			},
		},
		["Daclampers - Stormrage"] = {
		},
		["Forbizzle - Lightning's Blade"] = {
		},
		["Forbpal - Mal'Ganis"] = {
		},
		["Forbot - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 341.965724262067,
			},
		},
		["Worgentime - Mal'Ganis"] = {
		},
		["Saraessa - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 203.0661660310771,
			},
		},
		["Peroielor - Stormrage"] = {
		},
		["Forbinsham - Mal'Ganis"] = {
		},
		["Lelliana - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 349.215663842552,
			},
		},
		["Telanvier - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 235.527814939759,
			},
		},
		["Forbins - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 341.965724262067,
			},
		},
		["Threatdown - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 351.0694785907378,
			},
		},
		["Thatsabart - Mal'Ganis"] = {
		},
		["Trashbandito - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 345.5732356645696,
			},
		},
		["Ducker - Bleeding Hollow"] = {
		},
		["Garradagh - Stormrage"] = {
			["minimap"] = {
				["minimapPos"] = 345.0547447762012,
			},
		},
		["Olokrim - Mal'Ganis"] = {
			["minimap"] = {
				["minimapPos"] = 202.7650610731128,
			},
		},
		["Haruon - Mal'Ganis"] = {
		},
	},
}
AstralAffixes = {
	["rotation"] = {
	},
	["season_start_week"] = 241,
	["season_affix"] = 130,
}
AstralLists = {
	{
		["name"] = "GUILD",
		["units"] = {
			["Sukitas-Stormrage"] = true,
			["Scharole-Mal'Ganis"] = true,
			["Colonpow-Mal'Ganis"] = true,
			["Hunterprease-Mal'Ganis"] = true,
			["Matrixe-Stormrage"] = true,
			["Lilanthi-Mal'Ganis"] = true,
			["Izzactotems-Mal'Ganis"] = true,
			["Nagaruna-Mal'Ganis"] = true,
			["Thebigpoh-Mal'Ganis"] = true,
			["Simpolic-Stormrage"] = true,
			["Jackychancla-Mal'Ganis"] = true,
			["Lohpan-Mal'Ganis"] = true,
			["Grassroots-Mal'Ganis"] = true,
			["Gosudawn-Mal'Ganis"] = true,
			["Vithraldor-Mal'Ganis"] = true,
			["Chaosbreaker-Mal'Ganis"] = true,
			["Nianua-Stormrage"] = true,
			["Arec-Mal'Ganis"] = true,
			["Revez-Mal'Ganis"] = true,
			["Lightshift-Mal'Ganis"] = true,
			["Grìp-Mal'Ganis"] = true,
			["Pandamonius-Mal'Ganis"] = true,
			["Priestmir-Mal'Ganis"] = true,
			["Teachsham-Mal'Ganis"] = true,
			["Shaltar-Mal'Ganis"] = true,
			["Ragnoth-Mal'Ganis"] = true,
			["Shurely-Mal'Ganis"] = true,
			["Kenbear-Mal'Ganis"] = true,
			["Halfscoopz-Mal'Ganis"] = true,
			["Mcgrimmy-Mal'Ganis"] = true,
			["Effey-Stormrage"] = true,
			["Dëathblade-Mal'Ganis"] = true,
			["Soph-Stormrage"] = true,
			["Omegah-Mal'Ganis"] = true,
			["Wreckshop-Mal'Ganis"] = true,
			["Shârkey-Mal'Ganis"] = true,
			["Kevm-Mal'Ganis"] = true,
			["Hephty-Mal'Ganis"] = true,
			["Nize-Mal'Ganis"] = true,
			["Asorukmage-Mal'Ganis"] = true,
			["Chicobean-Mal'Ganis"] = true,
			["Paellas-Mal'Ganis"] = true,
			["Funtastic-Mal'Ganis"] = true,
			["Growthspurt-Mal'Ganis"] = true,
			["Tïnktïnk-Mal'Ganis"] = true,
			["Pillowqween-Mal'Ganis"] = true,
			["Pacified-Mal'Ganis"] = true,
			["Holybladë-Mal'Ganis"] = true,
			["Gooth-Mal'Ganis"] = true,
			["Didimiss-Mal'Ganis"] = true,
			["Haviboolan-Mal'Ganis"] = true,
			["Lelliana-Mal'Ganis"] = true,
			["Ninari-Stormrage"] = true,
			["Amgine-Mal'Ganis"] = true,
			["Gorjis-Mal'Ganis"] = true,
			["Munx-Stormrage"] = true,
			["Rightarm-Mal'Ganis"] = true,
			["Bigheàd-Mal'Ganis"] = true,
			["Riptycent-Mal'Ganis"] = true,
			["Rtp-Mal'Ganis"] = true,
			["Demohner-Mal'Ganis"] = true,
			["Andramantis-Mal'Ganis"] = true,
			["Hextrii-Mal'Ganis"] = true,
			["Deathgrippro-Stormrage"] = true,
			["Zîhark-Mal'Ganis"] = true,
			["Grimdh-Mal'Ganis"] = true,
			["Uwuclap-Mal'Ganis"] = true,
			["Nawtcryp-Mal'Ganis"] = true,
			["Lightarrow-Mal'Ganis"] = true,
			["Elmonroy-Stormrage"] = true,
			["Oups-Mal'Ganis"] = true,
			["Jarkatel-Mal'Ganis"] = true,
			["Dudunab-Mal'Ganis"] = true,
			["Münkybrewstr-Mal'Ganis"] = "Rives#1647",
			["Holysheepy-Mal'Ganis"] = true,
			["Grimxo-Mal'Ganis"] = true,
			["Eliean-Mal'Ganis"] = true,
			["Lilgrimmy-Mal'Ganis"] = true,
			["Batru-Mal'Ganis"] = true,
			["Màr-Mal'Ganis"] = true,
			["Rammara-Stormrage"] = true,
			["Bowhoe-Mal'Ganis"] = true,
			["Kungfusing-Stormrage"] = true,
			["Hifelicia-Mal'Ganis"] = true,
			["Ayat-Mal'Ganis"] = true,
			["Cheetosnmilk-Mal'Ganis"] = true,
			["Xaddy-Mal'Ganis"] = true,
			["Vëgëtä-Mal'Ganis"] = true,
			["Dominor-Mal'Ganis"] = true,
			["Oldcake-Mal'Ganis"] = true,
			["Ãmaya-Mal'Ganis"] = true,
			["Getrockhard-Stormrage"] = true,
			["Khain-Stormrage"] = true,
			["Dede-Mal'Ganis"] = true,
			["Bonechunks-Mal'Ganis"] = true,
			["Nulad-Mal'Ganis"] = true,
			["Caryundrwood-Mal'Ganis"] = true,
			["Lunabéllé-Stormrage"] = true,
			["Aleiya-Mal'Ganis"] = true,
			["Drogon-Stormrage"] = true,
			["Narra-Stormrage"] = true,
			["Shardster-Mal'Ganis"] = true,
			["Elliea-Mal'Ganis"] = true,
			["Giffp-Mal'Ganis"] = true,
			["Rhazzle-Mal'Ganis"] = true,
			["Thulldar-Mal'Ganis"] = true,
			["Akunza-Mal'Ganis"] = true,
			["Adriatikis-Mal'Ganis"] = "Adriatik#1980",
			["Sylainla-Mal'Ganis"] = true,
			["Moriiti-Mal'Ganis"] = true,
			["Qxi-Mal'Ganis"] = true,
			["Rickybobbie-Mal'Ganis"] = true,
			["Thanose-Mal'Ganis"] = true,
			["Finship-Mal'Ganis"] = true,
			["Feralfin-Mal'Ganis"] = true,
			["Selares-Mal'Ganis"] = true,
			["Nimbostratus-Mal'Ganis"] = true,
			["Imsilly-Mal'Ganis"] = true,
			["Yaamu-Stormrage"] = true,
			["Asminae-Mal'Ganis"] = true,
			["Rghtindaface-Mal'Ganis"] = true,
			["Drugame-Stormrage"] = true,
			["Aquista-Stormrage"] = true,
			["Slanèsh-Stormrage"] = true,
			["Kyomo-Stormrage"] = true,
			["Gooflinger-Mal'Ganis"] = true,
			["Wagsshaman-Mal'Ganis"] = "Wags#11572",
			["Sobieskildr-Stormrage"] = true,
			["Tripnonacid-Stormrage"] = true,
			["Giffhunts-Mal'Ganis"] = true,
			["Googlimoogli-Mal'Ganis"] = true,
			["Murlynd-Mal'Ganis"] = true,
			["Nyv-Mal'Ganis"] = true,
			["Rogueprease-Mal'Ganis"] = true,
			["Skiper-Mal'Ganis"] = true,
			["Getoffmymonk-Mal'Ganis"] = true,
			["Jhephbezos-Mal'Ganis"] = true,
			["Jadesoldier-Mal'Ganis"] = true,
			["Trinitii-Mal'Ganis"] = true,
			["Beamcake-Mal'Ganis"] = true,
			["Opezmode-Mal'Ganis"] = true,
			["Chilliboon-Stormrage"] = true,
			["Caomei-Mal'Ganis"] = true,
			["Yenafir-Mal'Ganis"] = true,
			["Resdorator-Mal'Ganis"] = true,
			["Tkerbs-Mal'Ganis"] = true,
			["Troglita-Mal'Ganis"] = true,
			["Sheemas-Mal'Ganis"] = true,
			["Thataintpee-Mal'Ganis"] = true,
			["Autzz-Mal'Ganis"] = true,
			["Rïnnoa-Mal'Ganis"] = true,
			["Elieva-Mal'Ganis"] = true,
			["Grimsha-Mal'Ganis"] = true,
			["Grumpyhick-Mal'Ganis"] = "Fletch#1522",
			["Sheepytotems-Mal'Ganis"] = true,
			["Trogz-Mal'Ganis"] = true,
			["Lycanhunt-Mal'Ganis"] = true,
			["Bearscoopz-Mal'Ganis"] = true,
			["Tazaran-Stormrage"] = true,
			["Bernt-Mal'Ganis"] = true,
			["Happy-Mal'Ganis"] = true,
			["Boyardaddy-Mal'Ganis"] = true,
			["Iammeatdaddy-Mal'Ganis"] = true,
			["Youma-Stormrage"] = true,
			["Debble-Mal'Ganis"] = true,
			["Rhazzldazzl-Mal'Ganis"] = true,
			["Demoniquinne-Stormrage"] = true,
			["Sheepyreroll-Mal'Ganis"] = true,
			["Krystallìne-Mal'Ganis"] = true,
			["Kwazy-Mal'Ganis"] = true,
			["Ilthdion-Stormrage"] = true,
			["Xerati-Mal'Ganis"] = true,
			["Monkprease-Mal'Ganis"] = true,
			["Rageboner-Mal'Ganis"] = true,
			["Sykotron-Stormrage"] = true,
			["Licky-Mal'Ganis"] = true,
			["Pixlistis-Mal'Ganis"] = true,
			["Derevik-Stormrage"] = true,
			["Burstbish-Mal'Ganis"] = true,
			["Faowinx-Mal'Ganis"] = true,
			["Picklesticks-Mal'Ganis"] = true,
			["Wagsdk-Mal'Ganis"] = true,
			["Appolonia-Mal'Ganis"] = true,
			["Öba-Mal'Ganis"] = true,
			["Noghue-Stormrage"] = true,
			["Stupidthick-Mal'Ganis"] = true,
			["Rira-Mal'Ganis"] = true,
			["Phizeal-Mal'Ganis"] = true,
			["Sharden-Mal'Ganis"] = true,
			["Adamddh-Mal'Ganis"] = true,
			["Visser-Mal'Ganis"] = true,
			["Hotfin-Mal'Ganis"] = true,
			["Deltacö-Mal'Ganis"] = true,
			["Trc-Mal'Ganis"] = true,
			["Chõnky-Mal'Ganis"] = true,
			["Vulpesumbra-Mal'Ganis"] = true,
			["Ohkurr-Stormrage"] = true,
			["Miriska-Mal'Ganis"] = true,
			["Aej-Mal'Ganis"] = true,
			["Spencev-Mal'Ganis"] = true,
			["Cyfiver-Mal'Ganis"] = true,
			["Druidfellow-Mal'Ganis"] = true,
			["Khornhunter-Mal'Ganis"] = true,
			["Debbers-Mal'Ganis"] = true,
			["Khornshaman-Mal'Ganis"] = true,
			["Fluffmcduff-Mal'Ganis"] = true,
			["Riraraptor-Mal'Ganis"] = true,
			["Feignedheph-Mal'Ganis"] = true,
			["Hitmonleeroy-Stormrage"] = true,
			["Sunsetrose-Stormrage"] = true,
			["Xïp-Mal'Ganis"] = true,
			["Beastarcana-Mal'Ganis"] = true,
			["Fishgobloop-Mal'Ganis"] = true,
			["Mortakhai-Mal'Ganis"] = true,
			["Queryhint-Stormrage"] = true,
			["Ludexx-Mal'Ganis"] = true,
			["Asoruk-Mal'Ganis"] = true,
			["Treecake-Mal'Ganis"] = true,
			["Azmael-Mal'Ganis"] = true,
			["Lifeorhonor-Mal'Ganis"] = true,
			["Foxmckloud-Mal'Ganis"] = "Krieger#1120",
			["Ezpzmode-Mal'Ganis"] = true,
			["Rickibobbi-Mal'Ganis"] = true,
			["Citador-Mal'Ganis"] = true,
			["Enigmathicc-Mal'Ganis"] = true,
			["Grexisys-Mal'Ganis"] = true,
			["Khyrality-Mal'Ganis"] = true,
			["Synbiote-Mal'Ganis"] = true,
			["Cyfiverr-Mal'Ganis"] = true,
			["Trcdk-Mal'Ganis"] = true,
			["Allisonfaith-Mal'Ganis"] = true,
			["Fênnin-Mal'Ganis"] = true,
			["Severà-Mal'Ganis"] = true,
			["Orshock-Mal'Ganis"] = true,
			["Moonquinne-Stormrage"] = true,
			["Shhmang-Mal'Ganis"] = true,
			["Fênnon-Mal'Ganis"] = true,
			["Deebers-Mal'Ganis"] = true,
			["Epain-Mal'Ganis"] = true,
			["Oba-Mal'Ganis"] = true,
			["Tarugala-Mal'Ganis"] = true,
			["Seishy-Mal'Ganis"] = true,
			["Quesö-Mal'Ganis"] = true,
			["Dokdok-Mal'Ganis"] = true,
			["Drsmoke-Mal'Ganis"] = true,
			["Huntnab-Mal'Ganis"] = true,
			["Bfxx-Mal'Ganis"] = true,
			["Lumin-Stormrage"] = true,
			["Mayv-Mal'Ganis"] = true,
			["Maisey-Mal'Ganis"] = true,
			["Lockmir-Mal'Ganis"] = true,
			["Gentank-Stormrage"] = true,
			["Moistymeat-Mal'Ganis"] = true,
			["Captsharkey-Mal'Ganis"] = true,
			["Ohner-Mal'Ganis"] = true,
			["Whiispmage-Mal'Ganis"] = true,
			["Pohnerino-Mal'Ganis"] = true,
			["Tótemtime-Stormrage"] = true,
			["Daikens-Stormrage"] = true,
			["Dìta-Mal'Ganis"] = true,
			["Khornia-Mal'Ganis"] = true,
			["Grantus-Stormrage"] = true,
			["Fluffygold-Stormrage"] = true,
			["Liicky-Mal'Ganis"] = true,
			["Metswin-Stormrage"] = true,
			["Rescope-Mal'Ganis"] = true,
			["Holybabe-Mal'Ganis"] = "Yojimbo#1435",
			["Lilryan-Mal'Ganis"] = true,
			["Carolock-Mal'Ganis"] = true,
			["Careyprice-Mal'Ganis"] = true,
			["Justhicar-Stormrage"] = true,
			["Lightchi-Mal'Ganis"] = true,
			["Kelpchi-Mal'Ganis"] = true,
			["Threatdown-Mal'Ganis"] = true,
			["Vandersky-Stormrage"] = true,
			["Shaminn-Mal'Ganis"] = true,
			["Delarinn-Mal'Ganis"] = true,
			["Sneakypeteqt-Mal'Ganis"] = true,
			["Sighbro-Mal'Ganis"] = true,
			["Theamista-Mal'Ganis"] = true,
			["Teachw-Mal'Ganis"] = true,
			["Darkdisciple-Stormrage"] = true,
			["Ohneener-Mal'Ganis"] = true,
			["Khyuss-Mal'Ganis"] = true,
			["Skeetshootin-Stormrage"] = true,
			["Moldyscoopz-Mal'Ganis"] = true,
			["Ditá-Mal'Ganis"] = true,
			["Dinklefartz-Mal'Ganis"] = true,
			["Amorloesh-Stormrage"] = true,
			["Ofo-Mal'Ganis"] = true,
			["Sharpbladez-Mal'Ganis"] = true,
			["Doodoosauce-Mal'Ganis"] = true,
			["Meissa-Mal'Ganis"] = true,
			["Liquidcooled-Mal'Ganis"] = true,
			["Bohemind-Mal'Ganis"] = true,
			["Eredrusia-Mal'Ganis"] = true,
			["Priestprease-Mal'Ganis"] = true,
			["Ashtalon-Mal'Ganis"] = true,
			["Radrussian-Mal'Ganis"] = true,
			["Volx-Mal'Ganis"] = true,
			["Kitori-Mal'Ganis"] = true,
			["Abadon-Mal'Ganis"] = true,
			["Iiquor-Mal'Ganis"] = true,
			["Coffeescrub-Mal'Ganis"] = true,
			["Grimrod-Mal'Ganis"] = true,
			["Calipali-Mal'Ganis"] = true,
			["Dinklefartss-Mal'Ganis"] = "Fletch#1522",
			["Firescoopz-Mal'Ganis"] = true,
			["Sheepyy-Mal'Ganis"] = true,
			["Revyve-Stormrage"] = true,
			["Trioxidane-Mal'Ganis"] = true,
			["Komie-Stormrage"] = true,
			["Nawtcrypt-Mal'Ganis"] = true,
			["Huntardbeast-Mal'Ganis"] = true,
			["Mannora-Mal'Ganis"] = true,
			["Croscope-Mal'Ganis"] = true,
			["Airaelen-Mal'Ganis"] = true,
			["Trioxid-Mal'Ganis"] = true,
			["Deadgoogs-Mal'Ganis"] = true,
			["Earthchic-Mal'Ganis"] = true,
			["Eremin-Mal'Ganis"] = true,
			["Aphollo-Mal'Ganis"] = true,
			["Auliä-Mal'Ganis"] = true,
			["Giff-Mal'Ganis"] = true,
			["Rolldajeff-Mal'Ganis"] = true,
			["Leiare-Stormrage"] = true,
			["Captsharke-Mal'Ganis"] = true,
			["Qwy-Mal'Ganis"] = true,
			["Aeonani-Stormrage"] = true,
			["Tempustfotm-Mal'Ganis"] = true,
			["Ripshotdh-Mal'Ganis"] = true,
			["Dhrira-Mal'Ganis"] = true,
			["Quigne-Stormrage"] = true,
			["Historyteach-Mal'Ganis"] = true,
			["Cheetaru-Mal'Ganis"] = true,
			["Giffkwondo-Mal'Ganis"] = true,
			["Edigawa-Mal'Ganis"] = true,
			["Xuencake-Mal'Ganis"] = true,
			["Pllfftt-Mal'Ganis"] = true,
			["Khornrogue-Mal'Ganis"] = true,
			["Leylìn-Mal'Ganis"] = true,
			["Deerbra-Mal'Ganis"] = true,
			["Deadcake-Mal'Ganis"] = true,
			["Pandadk-Mal'Ganis"] = true,
			["Kazstraza-Mal'Ganis"] = true,
			["Lickher-Mal'Ganis"] = true,
			["Zeusidon-Mal'Ganis"] = true,
			["Twerkeys-Mal'Ganis"] = true,
			["Keëf-Mal'Ganis"] = true,
			["Gryym-Stormrage"] = true,
			["Cyberdose-Mal'Ganis"] = true,
			["Delarynn-Mal'Ganis"] = true,
			["Göwron-Mal'Ganis"] = true,
			["Riasoowoo-Mal'Ganis"] = true,
			["Ppdx-Mal'Ganis"] = true,
			["Mattdaimon-Mal'Ganis"] = true,
			["Saintcaine-Mal'Ganis"] = "Krieger#1120",
			["Caelistis-Mal'Ganis"] = true,
			["Gingertail-Mal'Ganis"] = true,
			["Salazandar-Mal'Ganis"] = true,
			["Oobadoobadoo-Mal'Ganis"] = true,
			["Rexaj-Mal'Ganis"] = "Adriatik#1980",
			["Overdse-Mal'Ganis"] = true,
			["Quinnertia-Stormrage"] = true,
			["Proctorb-Mal'Ganis"] = true,
			["Staziel-Stormrage"] = true,
			["Dårkquiver-Stormrage"] = true,
			["Kegpanda-Mal'Ganis"] = true,
			["Moleboye-Mal'Ganis"] = "Rives#1647",
			["Trashbandito-Mal'Ganis"] = true,
			["Mãrtyr-Mal'Ganis"] = true,
			["Veelke-Stormrage"] = true,
			["Kelystia-Mal'Ganis"] = true,
			["Bloodhoundd-Mal'Ganis"] = true,
			["Pohner-Mal'Ganis"] = true,
			["Maayv-Mal'Ganis"] = true,
			["Hiringu-Mal'Ganis"] = true,
			["Choplock-Mal'Ganis"] = true,
			["Synsational-Mal'Ganis"] = true,
			["Hrira-Mal'Ganis"] = true,
			["Oreõ-Mal'Ganis"] = true,
			["Yensta-Mal'Ganis"] = "cimi#1692",
			["Mermo-Mal'Ganis"] = true,
			["Vlixi-Mal'Ganis"] = true,
			["Histryteachr-Mal'Ganis"] = true,
			["Troglit-Mal'Ganis"] = true,
			["Ducki-Mal'Ganis"] = true,
			["Threeofthem-Mal'Ganis"] = true,
			["Azrill-Mal'Ganis"] = true,
			["Cerceii-Mal'Ganis"] = true,
			["Felcutie-Mal'Ganis"] = true,
			["Monkeyhotep-Mal'Ganis"] = true,
			["Driedmangoes-Mal'Ganis"] = true,
			["Requinne-Stormrage"] = true,
			["Rhazimon-Mal'Ganis"] = true,
			["Odplz-Mal'Ganis"] = true,
			["Charissma-Mal'Ganis"] = true,
			["Chokela-Mal'Ganis"] = true,
			["Imindanger-Mal'Ganis"] = true,
			["Stokes-Stormrage"] = true,
			["Rebelwilson-Mal'Ganis"] = true,
			["Lastdonald-Mal'Ganis"] = true,
			["Loxle-Mal'Ganis"] = true,
			["Trcfrm-Mal'Ganis"] = true,
			["Flyrant-Mal'Ganis"] = true,
			["Crophmonk-Stormrage"] = true,
			["Lastdonovan-Mal'Ganis"] = true,
			["Iickher-Mal'Ganis"] = true,
			["Ùwù-Mal'Ganis"] = true,
			["Mekamao-Mal'Ganis"] = true,
			["Tërrors-Mal'Ganis"] = true,
			["Gnùmlock-Stormrage"] = true,
			["Siodis-Mal'Ganis"] = true,
			["Barretdestyr-Mal'Ganis"] = true,
			["Scog-Mal'Ganis"] = true,
			["Lilk-Mal'Ganis"] = true,
			["Morthalas-Mal'Ganis"] = true,
			["Tërror-Mal'Ganis"] = true,
			["Brotør-Mal'Ganis"] = true,
			["Dblqtrpoundr-Mal'Ganis"] = true,
			["Gormling-Mal'Ganis"] = true,
			["Telanvier-Mal'Ganis"] = true,
			["Stormpanda-Mal'Ganis"] = true,
			["Tempust-Mal'Ganis"] = true,
			["Arcusjr-Mal'Ganis"] = true,
			["Rageborne-Mal'Ganis"] = true,
			["Sukitaz-Stormrage"] = true,
			["Arcizzoth-Mal'Ganis"] = true,
			["Drainÿou-Stormrage"] = true,
			["Brolÿ-Mal'Ganis"] = true,
			["Ionox-Stormrage"] = true,
			["Suchflavor-Mal'Ganis"] = true,
			["Trcdn-Mal'Ganis"] = true,
			["Chonkaladin-Mal'Ganis"] = true,
			["Forbot-Mal'Ganis"] = true,
			["Arquinne-Stormrage"] = true,
			["Beerfish-Mal'Ganis"] = true,
			["Eclipsei-Stormrage"] = true,
			["Quinnesight-Stormrage"] = true,
			["Projectohner-Mal'Ganis"] = true,
			["Jody-Stormrage"] = true,
			["Sillygoose-Mal'Ganis"] = true,
			["Annoyed-Mal'Ganis"] = true,
			["Nomilk-Mal'Ganis"] = "Yojimbo#1435",
			["Mîá-Stormrage"] = true,
			["Mederas-Stormrage"] = true,
			["Kyshanna-Stormrage"] = true,
			["Teachx-Mal'Ganis"] = true,
			["Tokiwarteeth-Mal'Ganis"] = "Krieger#1120",
			["Lastdonna-Mal'Ganis"] = true,
			["Eckø-Mal'Ganis"] = true,
			["Darquinne-Stormrage"] = true,
			["Pyradice-Stormrage"] = true,
			["Shammir-Mal'Ganis"] = true,
			["Jaimei-Mal'Ganis"] = true,
			["Justinchill-Stormrage"] = true,
			["Wagsrogue-Mal'Ganis"] = true,
			["Felscoopz-Mal'Ganis"] = true,
			["Picklzz-Mal'Ganis"] = "Rives#1647",
			["Shamñcheese-Mal'Ganis"] = true,
			["Skillvanishd-Mal'Ganis"] = true,
			["Quinneshot-Stormrage"] = true,
			["Thiccscoopz-Mal'Ganis"] = true,
			["Sàxa-Mal'Ganis"] = true,
			["Maggottron-Mal'Ganis"] = true,
			["Fulfilled-Mal'Ganis"] = true,
			["Forbinai-Mal'Ganis"] = true,
			["Outflaw-Mal'Ganis"] = true,
			["Thassian-Stormrage"] = true,
			["Ovrrdose-Mal'Ganis"] = true,
			["Brook-Stormrage"] = true,
			["Ripshotbh-Mal'Ganis"] = true,
			["Berserkpanda-Mal'Ganis"] = true,
			["Archidell-Mal'Ganis"] = true,
			["Thulldeath-Mal'Ganis"] = true,
			["Tilthree-Mal'Ganis"] = true,
			["Kelpp-Mal'Ganis"] = true,
			["Carayle-Mal'Ganis"] = true,
			["Implicite-Mal'Ganis"] = true,
			["Forbiñ-Mal'Ganis"] = true,
			["Zandre-Mal'Ganis"] = true,
			["Hatmunn-Mal'Ganis"] = true,
			["Bfx-Mal'Ganis"] = true,
			["Moleboy-Mal'Ganis"] = "Rives#1647",
			["Reverandgoog-Mal'Ganis"] = true,
			["Urhsala-Mal'Ganis"] = true,
			["Scoopz-Mal'Ganis"] = true,
			["Forbins-Mal'Ganis"] = true,
			["Khornya-Mal'Ganis"] = true,
			["Gromit-Mal'Ganis"] = true,
			["Conglu-Mal'Ganis"] = true,
			["Liljefe-Mal'Ganis"] = true,
			["Eyenine-Mal'Ganis"] = true,
			["Thesmir-Mal'Ganis"] = true,
			["Iiger-Mal'Ganis"] = true,
			["Tiltpala-Mal'Ganis"] = true,
			["Tempustslb-Mal'Ganis"] = true,
			["Ooges-Mal'Ganis"] = true,
			["Arcusqt-Mal'Ganis"] = true,
			["Aiss-Stormrage"] = true,
			["Bwonshlongdi-Mal'Ganis"] = true,
			["Selfx-Mal'Ganis"] = true,
			["Overdosd-Mal'Ganis"] = true,
			["Aldafodr-Mal'Ganis"] = true,
			["Dewcipline-Mal'Ganis"] = true,
			["Heavenboy-Stormrage"] = true,
			["Restopaly-Mal'Ganis"] = true,
			["Whiispok-Mal'Ganis"] = true,
			["Cruelpala-Stormrage"] = true,
			["Hodarii-Mal'Ganis"] = true,
			["Trioxane-Mal'Ganis"] = true,
			["Plucknstuff-Stormrage"] = true,
			["Crypticus-Mal'Ganis"] = true,
			["Delarin-Mal'Ganis"] = true,
			["Pumpher-Mal'Ganis"] = true,
			["Sassycakes-Mal'Ganis"] = true,
			["Napolincmplx-Stormrage"] = true,
			["Yenstah-Mal'Ganis"] = true,
			["Caliwava-Mal'Ganis"] = true,
			["Karatebeaver-Mal'Ganis"] = true,
			["Khephc-Mal'Ganis"] = true,
			["Kelpii-Mal'Ganis"] = true,
			["Majinpohner-Mal'Ganis"] = true,
			["Anarané-Mal'Ganis"] = true,
			["Whiisphunt-Mal'Ganis"] = true,
			["Twoscoopz-Mal'Ganis"] = true,
			["Lilarux-Mal'Ganis"] = true,
			["Wafflehauze-Mal'Ganis"] = true,
			["Koiah-Stormrage"] = true,
			["Thillygooth-Mal'Ganis"] = true,
			["Tròika-Mal'Ganis"] = true,
			["Allasomorph-Mal'Ganis"] = true,
			["Palaminn-Mal'Ganis"] = true,
			["Tërrorblade-Mal'Ganis"] = true,
			["Nodtsal-Mal'Ganis"] = true,
			["Adamd-Mal'Ganis"] = "Adam#1968",
			["Jackychankla-Mal'Ganis"] = true,
			["Gluebe-Mal'Ganis"] = true,
			["Chankla-Mal'Ganis"] = true,
			["Valeshaman-Mal'Ganis"] = true,
			["Gixxy-Mal'Ganis"] = true,
			["Pandaprìest-Mal'Ganis"] = true,
			["Laddis-Stormrage"] = true,
			["Jasun-Mal'Ganis"] = true,
			["Pandathrall-Mal'Ganis"] = true,
			["Bassisraw-Mal'Ganis"] = true,
			["Holidays-Mal'Ganis"] = true,
			["Whiteclohner-Mal'Ganis"] = true,
			["Pennycilliin-Stormrage"] = true,
			["Thightanic-Mal'Ganis"] = true,
			["Lùñchbox-Stormrage"] = true,
			["Cuckedbyvpn-Mal'Ganis"] = true,
		},
	}, -- [1]
	{
		["name"] = "FRIENDS",
		["units"] = {
			["Ashyheals-Illidan"] = "Ash#1501",
			["Holybabe-Mal'Ganis"] = "Yojimbo#1435",
			["Grumpyhick-Mal'Ganis"] = "Fletch#1522",
			["Ashywar-Illidan"] = "Ash#1501",
			["Rhouge-Eonar"] = "wonnow#1655",
			["Adriatikis-Mal'Ganis"] = "Adriatik#1980",
			["Ashyhands-Tichondrius"] = "Ash#1501",
			["Nomilk-Mal'Ganis"] = "Yojimbo#1435",
			["Sÿmphonÿ-Area52"] = "wonnow#1655",
			["Reptar-Eonar"] = "wonnow#1655",
			["Wildcountryx-Mal'Ganis"] = "Wildcountryx#1761",
			["Foxmckloud-Mal'Ganis"] = "Krieger#1120",
			["Shyaria-Illidan"] = "Ash#1501",
			["Borkedmage-Tichondrius"] = "WillTheD#1707",
			["Rapter-Coilfang"] = "wonnow#1655",
			["Kruegor-Azgalor"] = "Aralain#1464",
			["Señorbueno-Mal'Ganis"] = "ceejchamp#1467",
			["Wagsrogue-Mal'Ganis"] = "Wags#11572",
			["Spamshock-Eonar"] = "wonnow#1655",
			["Aralain-Azgalor"] = "Aralain#1464",
			["Maggottron-Mal'Ganis"] = "Krieger#1120",
			["Griffpunch-Tichondrius"] = "WillTheD#1707",
			["Ashdru-Tichondrius"] = "Ash#1501",
			["Borkes-Tichondrius"] = "WillTheD#1707",
			["Oluwatobiloa-Sargeras"] = "ceejchamp#1467",
			["Moleboi-Mal'Ganis"] = "Rives#1647",
			["Adamdd-Mal'Ganis"] = "Adam#1968",
			["Lûkka-Tichondrius"] = "WillTheD#1707",
			["Münkybrewstr-Mal'Ganis"] = "Rives#1647",
			["Alone-Coilfang"] = "wonnow#1655",
			["Hibernate-Eonar"] = "wonnow#1655",
			["Rexaj-Mal'Ganis"] = "Adriatik#1980",
			["Adamd-Mal'Ganis"] = "Adam#1968",
			["Dinklefartz-Mal'Ganis"] = "Fletch#1522",
			["Dkyoudown-Tichondrius"] = "WillTheD#1707",
			["Adamddh-Mal'Ganis"] = true,
			["Haec-Tichondrius"] = "WillTheD#1707",
			["Livalinia-Area52"] = "wonnow#1655",
			["Yenstah-Mal'Ganis"] = "Yensta#1390",
			["Dubert-Mal'Ganis"] = "Yojimbo#1435",
			["Holybabes-Mal'Ganis"] = "Yojimbo#1435",
			["Eot-Tichondrius"] = "WillTheD#1707",
			["Reeptar-Eonar"] = "wonnow#1655",
			["Droodookin-Azgalor"] = "Aralain#1464",
			["Bwauck-Mal'Ganis"] = "wonnow#1655",
			["Yensta-Mal'Ganis"] = "cimi#1692",
			["Wagsdruid-Mal'Ganis"] = "Wags#11572",
			["Borkman-Tichondrius"] = "WillTheD#1707",
			["Dinklefarts-Mal'Ganis"] = "Fletch#1522",
			["Bulleseye-Tichondrius"] = "Bulldog#1622",
			["Ripkin-Goldrinn"] = "Bulldog#1622",
			["Tokiwarteeth-Mal'Ganis"] = "Krieger#1120",
			["Kriegerdots-Mal'Ganis"] = "Krieger#1120",
			["Lambofeeties-Area52"] = "wonnow#1655",
			["Deadcontent-Eonar"] = "wonnow#1655",
			["Dinklefartss-Mal'Ganis"] = "Fletch#1522",
			["Sleik-Azgalor"] = "Aralain#1464",
			["Saintcaine-Mal'Ganis"] = "Krieger#1120",
			["Xwildcountry-Mal'Ganis"] = "Wildcountryx#1761",
			["Kreshnar-Tichondrius"] = "WillTheD#1707",
			["Raptér-Area52"] = "wonnow#1655",
			["Oluwatobiloa-Mal'Ganis"] = "ceejchamp#1467",
			["Wagsshaman-Mal'Ganis"] = "Wags#11572",
			["Deadcontent-Area52"] = "wonnow#1655",
			["Emanrevelc-Tichondrius"] = "WillTheD#1707",
			["Serinin-Azgalor"] = "Aralain#1464",
			["Reeptar-Mal'Ganis"] = "wonnow#1655",
			["Ashyari-Illidan"] = "Ash#1501",
			["Moleboye-Mal'Ganis"] = "Rives#1647",
			["Topramon-Kil'jaeden"] = "TopRamon#1797",
			["Moleboy-Mal'Ganis"] = "Rives#1647",
			["Wagsmonk-Mal'Ganis"] = "Wags#11572",
			["Bulleseye-Dalaran"] = "Bulldog#1622",
			["Uwugrip-Area52"] = "wonnow#1655",
			["Molebuoy-Mal'Ganis"] = "Rives#1647",
			["Picklzz-Mal'Ganis"] = "Rives#1647",
			["Gaelfury-Mal'Ganis"] = "Krieger#1120",
		},
	}, -- [2]
}
AstralUnits = nil
